INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (1, 42, 'Rodriguez, Obrien and Hill Model X', 98.13, 15.15, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (2, 24, 'Moore, Allison and Burgess Model Y', 95.27, 65.84, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (3, 45, 'Delacruz-Jones Model Y', 79.15, 95.2, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (4, 14, 'Long-Harvey Model Y', 96.88, 50.77, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (5, 41, 'Bauer, Lopez and Williams Model 3', 63.16, 87.04, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (6, 28, 'Mcpherson, Hopkins and Lambert Model Y', 93.82, 25.13, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (7, 26, 'Reed, Atkinson and Jackson Model Y', 61.83, 21.37, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (8, 1, 'Martin-Turner Model S', 55.04, 44.95, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (9, 47, 'Mullins, Clark and Rodriguez Model X', 82.01, 60.35, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (10, 39, 'Nelson Inc Model X', 40.03, 58.03, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (11, 21, 'Young Inc Model Y', 82.23, 15.57, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (12, 21, 'Smith-Casey Model X', 78.34, 55.49, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (13, 13, 'Rodriguez-Gomez Model 3', 80.82, 55.59, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (14, 19, 'Cooke Group Model Y', 73.74, 44.43, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (15, 13, 'Baird-Moore Model Y', 55.95, 76.27, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (16, 9, 'Barnes Inc Model S', 60.54, 36.3, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (17, 21, 'Evans, Reid and Brown Model X', 51.19, 77.43, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (18, 45, 'Mckee Group Model 3', 95.57, 86.43, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (19, 21, 'Herrera-Rodriguez Model X', 76.73, 93.69, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (20, 15, 'Strickland, Campbell and Gibson Model 3', 73.38, 71.48, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (21, 50, 'Shaw, Davis and Grant Model Y', 64.01, 23.43, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (22, 18, 'Fuentes-Johnson Model 3', 44.27, 36.88, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (23, 18, 'Carter, Sullivan and Bell Model 3', 76.81, 56.89, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (24, 27, 'Bailey, Barron and Brown Model X', 64.06, 30.65, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (25, 12, 'Vang, Thomas and Church Model Y', 69.35, 14.35, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (26, 39, 'Ross LLC Model X', 75.43, 36.57, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (27, 11, 'Anthony-Salas Model 3', 83.38, 82.76, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (28, 50, 'Zamora LLC Model S', 95.01, 31.91, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (29, 14, 'Cowan, Riddle and Cherry Model X', 95.58, 94.43, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (30, 34, 'Joseph, Murillo and Fuentes Model Y', 96.4, 80.95, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (31, 30, 'Carter Ltd Model 3', 46.83, 54.4, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (32, 14, 'Martinez-Nguyen Model Y', 76.72, 58.03, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (33, 34, 'Smith-Prince Model Y', 69.31, 79.37, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (34, 20, 'Stewart-Hampton Model Y', 69.84, 79.48, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (35, 29, 'Johnson-Johnson Model 3', 40.09, 12.09, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (36, 33, 'Lee Inc Model S', 76.21, 76.73, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (37, 24, 'Coleman-Goodwin Model Y', 65.6, 80.99, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (38, 25, 'Kelly, Martin and Conner Model 3', 52.64, 58.57, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (39, 42, 'Hunt Ltd Model X', 94.89, 44.22, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (40, 40, 'Duncan and Sons Model 3', 60.43, 82.52, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (41, 10, 'Mcguire, Yoder and Kim Model 3', 67.38, 38.44, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (42, 24, 'Nelson-Barr Model S', 40.99, 97.94, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (43, 36, 'Garcia, Martin and Hall Model Y', 75.76, 62.73, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (44, 10, 'Young Ltd Model X', 69.65, 78.77, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (45, 22, 'Nguyen-Stone Model Y', 93.49, 67.33, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (46, 5, 'Johnson Group Model X', 59.0, 88.12, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (47, 3, 'Bright, Mcdowell and Luna Model X', 59.41, 50.25, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (48, 39, 'Wells and Sons Model X', 55.99, 41.56, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (49, 8, 'Chen PLC Model S', 89.34, 99.53, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (50, 35, 'Hanson and Sons Model X', 44.15, 95.4, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (51, 18, 'Butler, Melton and Evans Model 3', 53.51, 43.57, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (52, 47, 'Ballard, Shaw and Townsend Model S', 94.84, 51.75, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (53, 8, 'Thornton LLC Model Y', 47.1, 15.95, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (54, 49, 'Costa-Baker Model 3', 64.21, 74.83, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (55, 26, 'Little, Garcia and Jackson Model S', 88.7, 13.81, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (56, 3, 'Wright Ltd Model 3', 63.56, 90.5, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (57, 11, 'Reyes, Wise and Soto Model X', 51.61, 67.92, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (58, 30, 'Ford, Gaines and Woodard Model S', 93.85, 13.49, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (59, 12, 'Peters, Donovan and Miller Model X', 83.17, 92.15, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (60, 13, 'Johnson, Hale and Daniel Model X', 87.5, 16.32, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (61, 40, 'Juarez-Kelly Model X', 71.52, 64.59, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (62, 39, 'Clark, Jones and Hubbard Model S', 81.65, 51.59, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (63, 18, 'White PLC Model 3', 75.91, 53.14, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (64, 18, 'Williams, Sullivan and Tucker Model Y', 68.73, 93.87, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (65, 20, 'Lambert and Sons Model S', 59.09, 58.3, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (66, 5, 'Moore, Johnson and Murphy Model S', 68.75, 82.39, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (67, 8, 'Matthews, Wade and Washington Model X', 43.36, 46.28, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (68, 44, 'Bradley, Bell and Thornton Model Y', 48.53, 85.74, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (69, 5, 'Marks, Gibson and Hardy Model Y', 85.26, 67.34, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (70, 39, 'Allen-Ramos Model S', 41.99, 29.36, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (71, 9, 'Logan, Barnett and Miles Model 3', 67.51, 65.39, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (72, 32, 'Mann, Ruiz and Garcia Model Y', 71.68, 58.01, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (73, 35, 'Knight, Reynolds and Johnson Model Y', 52.1, 56.83, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (74, 10, 'Warner and Sons Model 3', 58.6, 13.28, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (75, 29, 'Savage Ltd Model S', 82.93, 86.42, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (76, 33, 'Archer-Fields Model Y', 97.69, 46.78, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (77, 18, 'Galvan-Hester Model S', 63.85, 88.85, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (78, 45, 'Scott LLC Model Y', 45.98, 43.28, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (79, 39, 'Silva-Lester Model Y', 73.48, 75.66, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (80, 46, 'Santana, Caldwell and Church Model Y', 71.76, 59.22, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (81, 4, 'Evans Group Model X', 93.44, 66.31, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (82, 24, 'Cunningham-Warren Model X', 47.49, 31.86, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (83, 24, 'Murphy, Brown and Johnson Model X', 59.48, 46.48, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (84, 29, 'Leonard Ltd Model Y', 79.27, 20.32, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (85, 26, 'Young Ltd Model Y', 42.97, 77.71, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (86, 7, 'Booth, Anderson and Wall Model X', 97.74, 35.85, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (87, 14, 'Bradley-Murphy Model X', 97.05, 70.67, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (88, 24, 'French-Herrera Model 3', 45.98, 91.53, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (89, 31, 'Holmes LLC Model 3', 73.88, 27.95, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (90, 40, 'Nguyen-Warren Model X', 87.9, 95.12, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (91, 11, 'Ibarra Inc Model Y', 84.06, 32.62, 4);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (92, 24, 'Smith, Jones and Ramos Model Y', 59.35, 74.42, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (93, 4, 'Rodriguez Inc Model X', 81.66, 64.71, 3);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (94, 47, 'Ball LLC Model 3', 48.25, 44.09, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (95, 6, 'Black-Jenkins Model S', 84.25, 10.17, 1);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (96, 4, 'Meza Group Model S', 43.86, 14.14, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (97, 50, 'Bradshaw-Smith Model X', 64.28, 67.05, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (98, 19, 'Davis-Hunter Model 3', 88.22, 79.5, 5);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (99, 6, 'Robinson Inc Model Y', 51.39, 57.5, 2);
INSERT INTO EVs (ev_id, owner_id, model, battery_capacity, soc, priority_level) VALUES (100, 19, 'Ray, Vaughn and Young Model Y', 58.66, 41.54, 1);
